server:
  port: 8082
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      routes:
        - id: users-status-check
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/users/status/check
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ws/users/status/check, /users/status/check
        - id: users-h2-db
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/h2
            - Method=GET
          filters:
            - RewritePath=/users-ws/h2, /h2-console

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka


# Method=GET, POST, etc - to allow other request methods