server:
  port: 8082
spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8012
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      routes:
        - id: users-status-check
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/users/status
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ws/users/status, /users/status/check
            - AuthorizationHeaderFilter
        - id: users-h2-db
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/h2
            - Method=GET
          filters:
            - RewritePath=/users-ws/h2, /h2-console
        - id: users-controller
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/users
            - Method=GET,POST
          filters:
            - RewritePath=/users-ws/users, /users
        - id: users-login
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/signin
            - Method=POST
          filters:
            - RewritePath=/users-ws/signin, /signin
        - id: user-ws-actuator
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/actuator/**
            - Method=GET
          filters:
            - RewritePath=/users-ws/(?<segment>.*), /$\{segment}
  rabbitmq:
    host: localhost
    port: 5671
    username: user
    password: password

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka


# Method=GET, POST, etc - to allow other request methods

# actuator endpoint config
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,health,mappings